# Generated by Django 5.2.17 on 2026-10-03 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scan_hidden_from_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomiclog',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agronomic_logs', to='core.scan'),
        ),
    ]
