# Generated by Django 5.2.17 on 2026-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agronomiclog_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='agronomiclog',
            name='recommendations_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
