# Generated by Django 5.2.17 on 2026-10-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agronomiclog_recommendations_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
