from django.urls import path

from . import views


urlpatterns = [
    path("", views.portal, name="portal"),
    path("admin-access", views.admin_access, name="admin_access"),
    path("homepage", views.homepage, name="homepage"),
    path("farmer/recommendations", views.farmer_recommendations, name="farmer_recommendations"),
    path("farmer/agronomic-logs", views.farmer_agronomic_logs, name="farmer_agronomic_logs"),
    path("farmer/cv-upload/<int:upload_id>/delete", views.delete_cv_upload, name="delete_cv_upload"),
    path("api/scan/predict", views.api_scan_predict, name="api_scan_predict"),
    path("calculate", views.calculate_results, name="calculate_results"),
    path("farmer/settings", views.farmer_settings, name="farmer_settings"),
    path("farmer/feedback", views.farmer_feedback, name="farmer_feedback"),
    path("admin", views.admin_portal, name="admin_portal"),
    path("admin/farmers", views.admin_farmers, name="admin_farmers"),
    path("admin/farmers/<int:user_id>/edit", views.admin_farmer_edit, name="admin_farmer_edit"),
    path("admin/monitoring", views.admin_monitoring, name="admin_monitoring"),
    path("admin/models", views.admin_models, name="admin_models"),
    path("admin/reports", views.admin_reports, name="admin_reports"),
    path("admin/communications", views.admin_communications, name="admin_communications"),
    path("admin-login", views.admin_login, name="admin_login"),
    path("superadmin-login", views.superadmin_login, name="superadmin_login"),
    path("admin-setup", views.admin_setup, name="admin_setup"),
    path("admin-register", views.admin_register, name="admin_register"),
    path("superadmin-register", views.superadmin_register, name="superadmin_register"),
    path("admin-reset", views.admin_reset, name="admin_reset"),
    path("superadmin", views.superadmin_portal, name="superadmin_portal"),
    path("superadmin/admins/create", views.superadmin_create_admin, name="superadmin_create_admin"),
    path("superadmin/admins/role", views.superadmin_update_role, name="superadmin_update_role"),
    path("superadmin/admins/archive", views.superadmin_archive_admin, name="superadmin_archive_admin"),
    path("superadmin/users/archive", views.superadmin_archive_user, name="superadmin_archive_user"),
    path("superadmin/users/<int:user_id>", views.superadmin_user_details, name="superadmin_user_details"),
    path("superadmin/users/restore", views.superadmin_restore_user, name="superadmin_restore_user"),
    path("admin-logout", views.admin_logout, name="admin_logout"),
    path("auth", views.auth, name="auth"),
    path("auth/register-success", views.auth_register_success, name="auth_register_success"),
    path("logout", views.logout, name="logout"),
    path("scan/new", views.scan_new, name="scan_new"),
    path("superadmin/settings", views.superadmin_settings, name="superadmin_settings"),
    path("superadmin/reports", views.superadmin_reports, name="superadmin_reports"),
    path("superadmin/reports/download", views.superadmin_reports_download, name="superadmin_reports_download"),
    path("superadmin/audit", views.superadmin_audit, name="superadmin_audit"),
]
